sudo: required
language: node_js python
node_js:
  - "6"
python:
  - "3.5"
  - "3.6"
before_install:
  - python3 -V
  - sudo pip install wikiparser
install:
  - npm install
  - sudo pip install wikiparser
script: "npm test"