sudo: required
language: node_js
node_js:
  - "6"
python:
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install python3-setuptools
  - sudo easy_install3 pip
install:
  - npm install
  - virtualenv -p /usr/bin/python3 py3env
  - source py3env/bin/activate
  - sudo python -m pip install wikiparser
script: "npm test"