sudo: required
language: node_js
node_js:
  - "6"
python:
  - "3.6"
before_install:
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  - sudo pip install wikiparser
install:
  - npm install
  - sudo pip install wikiparser
language: node_js
script: "npm test"