sudo: required
language: python
node_js:
  - "6"
python:
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
install:
  - npm install
  - sudo pip install wikiparser
  - sudo python -m pip install wikiparser
script: "npm test"